version: '3.2'
volumes:
  caddy: {}

services:
  your-app-ts:
    build: .
    volumes:
      - ./:/app/
      - ./node_modules/:/app/node_modules/
    env_file:
      - .env
    ports:
      - '3000:3000'
    links:
      - mongo
  
  mongo:
    image: mongo:4.2.1-bionic
    volumes:
      - ./mongo-data/:/data/db/
      - ./mongo-backup/:/mongo-backup/
    ports:
      - "27017:27017"

  caddy:
    build:
      context: .
      dockerfile: ./docker_compose/caddy/Dockerfile
    depends_on:
      - your-app-ts
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - '0.0.0.0:443:443'
      